
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";

import { Background } from "@/components/ui/Background";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Ajijul Islam's Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ThemeProvider
          attribute="class"
          defaultTheme="light"
          enableSystem
          disableTransitionOnChange
        >
          <div>
          <Background>{children}</Background>
          </div>
        </ThemeProvider>
      </body>
    </html>
  );
}
